name: "Check"
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup terraform
      uses: hashicorp/setup-terraform@main
    - name: Format check
      run: terraform fmt -check
